
import type { CrystalData } from '@/types/design';

export type { CrystalData };

export type CrystalTypeMapping = Record<string, CrystalData>;

// Notes:
// - displayName: Should be "Chinese Name (English Name)" for proper translation parsing by getCrystalDisplayName.
// - englishName: The canonical English name.
// - availableColors: Array of English color names.
// - specificInclusions: Keys for inclusions unique or highly characteristic of this crystal. Must be translated in locale files.
// - Universal inclusions (defined in types/design.ts) are added dynamically by the form.

export const crystalTypeMapping: CrystalTypeMapping = {
  Amazonite: {
    displayName: '天河石 (Amazonite)',
    englishName: 'Amazonite',
    availableColors: ['Light Green', 'Blue-Green', 'Turquoise Green', 'Pale Aqua'],
    specificInclusions: ['inclusion_white_streaks_amazonite', 'inclusion_perthitic_texture'],
    healingProperties: ['prop_soothing_calm', 'prop_communication_truth', 'prop_emotional_trauma_healing', 'prop_balancing_masculine_feminine'],
    chakra: ['chakra_heart', 'chakra_throat'],
    element: ['element_water', 'element_earth'],
    zodiac: ['zodiac_virgo', 'zodiac_aquarius'],
  },
  Amethyst: {
    displayName: '紫水晶 (Amethyst)',
    englishName: 'Amethyst',
    availableColors: ['Purple', 'Lavender', 'Deep Purple', 'Lilac'],
    specificInclusions: ['inclusion_goethite_specific_amethyst', 'inclusion_cacoxenite_specific_amethyst', 'inclusion_chevron_markings_amethyst', 'inclusion_zebra_stripes_amethyst'],
    healingProperties: ['prop_spirituality', 'prop_protection', 'prop_calmness', 'prop_intuition'],
    chakra: ['chakra_thirdEye', 'chakra_crown'],
    element: ['element_air', 'element_water', 'element_ether'],
    zodiac: ['zodiac_pisces', 'zodiac_virgo', 'zodiac_aquarius', 'zodiac_sagittarius'],
  },
  Angelite: {
    displayName: '天使石 (Angelite)',
    englishName: 'Angelite',
    availableColors: ['Light Blue', 'Pale Blue', 'White with blue tint'],
    specificInclusions: ['inclusion_white_spots_angelite', 'inclusion_fine_grained_texture_angelite'],
    healingProperties: ['prop_angelic_connection_angelite', 'prop_gentle_communication', 'prop_peace_serenity', 'prop_spiritual_awareness'],
    chakra: ['chakra_throat', 'chakra_thirdEye', 'chakra_crown'],
    element: ['element_air', 'element_wind'],
    zodiac: ['zodiac_aquarius', 'zodiac_pisces']
  },
  Aquamarine: {
    displayName: '海蓝宝 (Aquamarine)',
    englishName: 'Aquamarine',
    availableColors: ["Pale Blue", "Blue-Green", "Light Blue", "Sky Blue", "Sea Green"],
    specificInclusions: ["inclusion_hollow_tubes_aqua_specific", "inclusion_parallel_growth_tubes_aqua_specific", "inclusion_rain_like_inclusions_aqua", "inclusion_biotite_flakes_aqua_specific", "inclusion_muscovite_aqua"],
    healingProperties: ["prop_courage_communication", "prop_calming_soothing", "prop_truth_expression", "prop_spiritual_awareness_aqua"],
    chakra: ["chakra_throat", "chakra_heart"],
    element: ["element_water"],
    zodiac: ["zodiac_aries", "zodiac_gemini", "zodiac_pisces", "zodiac_aquarius"]
  },
  Auralite23: {
    displayName: '极光23 (Auralite-23)',
    englishName: 'Auralite-23',
    availableColors: ['Deep Purple with Red Tip', 'Chevron Amethyst patterns', 'Multi-layered hues'],
    specificInclusions: ['inclusion_chevron_patterns_auralite23', 'inclusion_red_cap_auralite23', 'inclusion_multi_mineral_layers_auralite23', 'inclusion_titanite_green_spots_auralite23'],
    healingProperties: ['prop_deep_meditation', 'prop_spiritual_healing', 'prop_releasing_patterns', 'prop_calm_connection'],
    chakra: ['chakra_thirdEye', 'chakra_crown'],
    element: ['element_air', 'element_ether'],
    zodiac: ['zodiac_all'],
  },
  BlackTourmaline: {
    displayName: '黑碧玺 (Black Tourmaline)',
    englishName: 'Black Tourmaline',
    availableColors: ["Black", "Very Dark Brown"],
    specificInclusions: ["inclusion_striations_tourmaline_specific", "inclusion_quartz_intergrowth_tourmaline_specific", "inclusion_mica_flakes_tourmaline_specific", "inclusion_feldspar_matrix_tourmaline"],
    healingProperties: ["prop_protection_emf", "prop_grounding_energy", "prop_negativity_shield", "prop_purification"],
    chakra: ["chakra_root"],
    element: ["element_earth"],
    zodiac: ["zodiac_capricorn", "zodiac_libra"]
  },
  Bloodstone: {
    displayName: '血石 (Bloodstone)',
    englishName: 'Bloodstone',
    availableColors: ['Dark Green with Red Spots', 'Green with Red Streaks'],
    specificInclusions: ['inclusion_red_hematite_spots_bloodstone', 'inclusion_chalcedony_matrix_bloodstone'],
    healingProperties: ['prop_purification_blood', 'prop_courage_selflessness', 'prop_grounding_protective_bloodstone', 'prop_reduces_irritability'],
    chakra: ['chakra_root', 'chakra_heart'],
    element: ['element_earth'],
    zodiac: ['zodiac_aries', 'zodiac_libra', 'zodiac_pisces']
  },
  BlueLaceAgate: {
    displayName: '蓝纹玛瑙 (Blue Lace Agate)',
    englishName: 'Blue Lace Agate',
    availableColors: ['Pale Blue with White Bands', 'Light Blue', 'Lavender Blue'],
    specificInclusions: ['inclusion_fine_banding_bluelace', 'inclusion_fortification_patterns_bluelace'],
    healingProperties: ['prop_calm_communication_angelic', 'prop_nurturing_supportive', 'prop_neutralizes_anger', 'prop_cools_inflammation'],
    chakra: ['chakra_throat'],
    element: ['element_water', 'element_air'],
    zodiac: ['zodiac_pisces', 'zodiac_gemini']
  },
  BotswanaAgate: {
    displayName: '博茨瓦纳玛瑙 (Botswana Agate)',
    englishName: 'Botswana Agate',
    availableColors: ['Grey with pink and white bands', 'Brown with white bands', 'Pinkish grey bands'],
    specificInclusions: ['inclusion_fine_parallel_banding_botswana', 'inclusion_fortification_eye_patterns_botswana'],
    healingProperties: ['prop_comforting_protective_botswana', 'prop_solutions_not_problems', 'prop_helps_release_repression', 'prop_aids_smoking_cessation'],
    chakra: ['chakra_sacral', 'chakra_root'],
    element: ['element_earth', 'element_air'],
    zodiac: ['zodiac_scorpio', 'zodiac_gemini']
  },
  Carnelian: {
    displayName: '红玉髓 (Carnelian)',
    englishName: 'Carnelian',
    availableColors: ['Orange', 'Red-Orange', 'Pinkish-Orange', 'Brownish Red'],
    specificInclusions: ['inclusion_banding_carnelian', 'inclusion_cloudy_patterns'],
    healingProperties: ['prop_vitality_motivation_creativity', 'prop_courage_leadership', 'prop_restoring_energy', 'prop_grounding_sacral'],
    chakra: ['chakra_root', 'chakra_sacral', 'chakra_solarPlexus'],
    element: ['element_fire'],
    zodiac: ['zodiac_taurus', 'zodiac_cancer', 'zodiac_leo', 'zodiac_virgo'],
  },
  Celestite: {
    displayName: '天青石 (Celestite)',
    englishName: 'Celestite',
    availableColors: ['Pale Blue', 'Sky Blue', 'White', 'Clear'],
    specificInclusions: ['inclusion_geode_formation_celestite', 'inclusion_tabular_crystals_celestite'],
    healingProperties: ['prop_angelic_communication', 'prop_divine_guidance', 'prop_high_spiritual_energy', 'prop_soothing_sleep'],
    chakra: ['chakra_throat', 'chakra_thirdEye', 'chakra_crown'],
    element: ['element_air', 'element_water'],
    zodiac: ['zodiac_gemini', 'zodiac_libra']
  },
  Chrysocolla: {
    displayName: '硅孔雀石 (Chrysocolla)',
    englishName: 'Chrysocolla',
    availableColors: ['Cyan', 'Green', 'Blue-Green', 'Turquoise Green'],
    specificInclusions: ['inclusion_malachite_intergrowth_chryso', 'inclusion_quartz_druzy_chryso', 'inclusion_black_oxide_veins'],
    healingProperties: ['prop_goddess_energy', 'prop_empowerment_feminine', 'prop_tranquility_communication', 'prop_draws_out_guilt'],
    chakra: ['chakra_throat', 'chakra_heart'],
    element: ['element_water'],
    zodiac: ['zodiac_gemini', 'zodiac_virgo', 'zodiac_taurus']
  },
  Citrine: {
    displayName: '黄水晶 (Citrine)',
    englishName: 'Citrine',
    availableColors: ['Yellow', 'Golden Yellow', 'Orange-Yellow', 'Brownish Yellow'],
    specificInclusions: ['inclusion_smoky_phantoms_citrine', 'inclusion_rainbows_internal_citrine', 'inclusion_healed_fractures_citrine'],
    healingProperties: ['prop_abundance', 'prop_manifestation', 'prop_creativity', 'prop_optimism'],
    chakra: ['chakra_solarPlexus', 'chakra_sacral', 'chakra_crown'],
    element: ['element_fire'],
    zodiac: ['zodiac_aries', 'zodiac_gemini', 'zodiac_leo', 'zodiac_libra'],
  },
  ClearQuartz: {
    displayName: '白水晶 (Clear Quartz)',
    englishName: 'Clear Quartz',
    availableColors: ['Clear', 'White'],
    specificInclusions: ['inclusion_chlorite_phantom_clear', 'inclusion_rutile_needles_clear', 'inclusion_tourmaline_needles_clear', 'inclusion_hematite_flakes_clear', 'inclusion_rainbow_fractures_clear', 'inclusion_record_keepers_clear'],
    healingProperties: ['prop_amplification', 'prop_clarity', 'prop_healing', 'prop_energy_cleansing'],
    chakra: ['chakra_all'],
    element: ['element_all'],
    zodiac: ['zodiac_all'],
  },
  DendriticAgate: {
    displayName: '树枝状玛瑙 (Dendritic Agate)',
    englishName: 'Dendritic Agate',
    availableColors: ['Translucent with dark inclusions', 'White with dark inclusions', 'Yellowish with dark inclusions'],
    specificInclusions: ['inclusion_tree_like_dendrites', 'inclusion_fern_like_patterns'],
    healingProperties: ['prop_fullness_abundance_dendritic', 'prop_perseverance_patience', 'prop_connection_to_earth_dendritic', 'prop_self_examination'],
    chakra: ['chakra_root', 'chakra_crown'],
    element: ['element_earth'],
    zodiac: ['zodiac_gemini', 'zodiac_virgo']
  },
  FireAgate: {
    displayName: '火玛瑙 (Fire Agate)',
    englishName: 'Fire Agate',
    availableColors: ['Brown with iridescent colors', 'Orange-red flashes', 'Green and gold flashes'],
    specificInclusions: ['inclusion_iridescent_goethite_limonite_fire', 'inclusion_botryoidal_chalcedony_fire'],
    healingProperties: ['prop_deep_grounding_fire', 'prop_protective_shield_fire', 'prop_stimulates_vitality_fire', 'prop_dispels_fear_fire'],
    chakra: ['chakra_sacral', 'chakra_root'],
    element: ['element_fire'],
    zodiac: ['zodiac_aries', 'zodiac_leo', 'zodiac_sagittarius']
  },
  Fluorite: {
    displayName: '萤石 (Fluorite)',
    englishName: 'Fluorite',
    availableColors: ['Purple', 'Green', 'Clear', 'Blue', 'Yellow', 'Rainbow (banded)'],
    specificInclusions: ['inclusion_color_banding_fluorite', 'inclusion_cubic_crystals_fluorite', 'inclusion_phantom_fluorite', 'inclusion_thermoluminescence'],
    healingProperties: ['prop_focus_clarity_concentration', 'prop_aura_cleansing', 'prop_neutralizes_stress', 'prop_improves_coordination'],
    chakra: ['chakra_heart', 'chakra_throat', 'chakra_thirdEye'],
    element: ['element_air', 'element_water'],
    zodiac: ['zodiac_capricorn', 'zodiac_pisces'],
  },
  Garnet: {
    displayName: '石榴石 (Garnet)',
    englishName: 'Garnet',
    availableColors: ["Deep Red", "Reddish Brown", "Orange", "Pink", "Purple", "Red-Purple"],
    specificInclusions: ["inclusion_rutile_needles_garnet_specific", "inclusion_asterism_garnet_specific", "inclusion_chromite_pyrope_garnet", "inclusion_apatite_garnet_specific"],
    healingProperties: ["prop_energy_vitality", "prop_passion_love", "prop_protection_aura", "prop_manifestation_goals"],
    chakra: ["chakra_root", "chakra_heart", "chakra_sacral"],
    element: ["element_fire", "element_earth"],
    zodiac: ["zodiac_aries", "zodiac_leo", "zodiac_virgo", "zodiac_capricorn", "zodiac_aquarius"]
  },
  GreenAventurine: {
    displayName: '绿东陵 (Green Aventurine)',
    englishName: 'Green Aventurine',
    availableColors: ['Green', 'Light Green', 'Sparkly Green'],
    specificInclusions: ['inclusion_fuchsite_mica_aventurine', 'inclusion_aventurescence_aventurine'],
    healingProperties: ['prop_luck_opportunity', 'prop_heart_healer_comforter', 'prop_prosperity_wealth', 'prop_calming_anger'],
    chakra: ['chakra_heart'],
    element: ['element_water', 'element_earth'],
    zodiac: ['zodiac_aries', 'zodiac_leo', 'zodiac_taurus'],
  },
  Hematite: {
    displayName: '赤铁矿 (Hematite)',
    englishName: 'Hematite',
    availableColors: ['Metallic Grey', 'Black', 'Reddish Brown (raw form)'],
    specificInclusions: ['inclusion_botryoidal_hematite', 'inclusion_specular_hematite', 'inclusion_red_ochre_coating'],
    healingProperties: ['prop_grounding_balancing', 'prop_focus_concentration', 'prop_absorbing_negativity', 'prop_strengthening_willpower'],
    chakra: ['chakra_root'],
    element: ['element_earth', 'element_fire'],
    zodiac: ['zodiac_aries', 'zodiac_aquarius'],
  },
  HerkimerDiamond: {
    displayName: '闪灵钻 (Herkimer Diamond)',
    englishName: 'Herkimer Diamond',
    availableColors: ['Ultra Clear', 'Smoky', 'With black carbon inclusions'],
    specificInclusions: ['inclusion_black_carbon_herkimer', 'inclusion_enhydro_herkimer', 'inclusion_double_terminated'],
    healingProperties: ['prop_attunement_stone', 'prop_amplifies_spiritual_energy', 'prop_dream_work_recall', 'prop_detoxification_herkimer'],
    chakra: ['chakra_thirdEye', 'chakra_crown'],
    element: ['element_storm'],
    zodiac: ['zodiac_aries', 'zodiac_sagittarius'],
  },
  Howlite: {
    displayName: '白松石 (Howlite)',
    englishName: 'Howlite',
    availableColors: ['White with grey veins', 'White'],
    specificInclusions: ['inclusion_grey_webbing_howlite', 'inclusion_nodular_form_howlite'],
    healingProperties: ['prop_calm_patience', 'prop_aids_sleep_insomnia', 'prop_absorbs_anger', 'prop_strengthens_memory'],
    chakra: ['chakra_crown', 'chakra_all'],
    element: ['element_air'],
    zodiac: ['zodiac_gemini', 'zodiac_virgo']
  },
  Kunzite: {
    displayName: '紫锂辉石 (Kunzite)',
    englishName: 'Kunzite',
    availableColors: ['Pink', 'Lilac', 'Pale Pink', 'Clear'],
    specificInclusions: ['inclusion_cleavage_planes_kunzite', 'inclusion_striations_kunzite_vertical'],
    healingProperties: ['prop_divine_love', 'prop_emotional_healing_kunzite', 'prop_removes_obstacles', 'prop_high_vibration'],
    chakra: ['chakra_heart', 'chakra_crown'],
    element: ['element_water', 'element_ether'],
    zodiac: ['zodiac_taurus', 'zodiac_leo', 'zodiac_scorpio']
  },
  Kyanite: {
    displayName: '蓝晶石 (Kyanite)',
    englishName: 'Kyanite',
    availableColors: ['Blue', 'Black', 'Green', 'Orange'],
    specificInclusions: ['inclusion_bladed_crystals_kyanite', 'inclusion_striations_kyanite', 'inclusion_color_zoning_kyanite'],
    healingProperties: ['prop_attunement_meditation', 'prop_clearing_energy_blockages', 'prop_does_not_hold_negativity', 'prop_encourages_self_expression'],
    chakra: ['chakra_throat', 'chakra_thirdEye', 'chakra_all'],
    element: ['element_air', 'element_storm'],
    zodiac: ['zodiac_aries', 'zodiac_taurus', 'zodiac_libra', 'zodiac_pisces'],
  },
  Labradorite: {
    displayName: '拉长石 (Labradorite)',
    englishName: 'Labradorite',
    availableColors: ['Grey-Green', 'Dark Grey', 'Black', 'Blue Flash', 'Green Flash', 'Gold Flash', 'Rainbow Flash'],
    specificInclusions: ['inclusion_labradorescence_effect_labradorite', 'inclusion_ilmenite_needles_labradorite', 'inclusion_magnetite_crystals_labradorite'],
    healingProperties: ['prop_transformation', 'prop_protection', 'prop_strengthens_intuition', 'prop_magic'],
    chakra: ['chakra_thirdEye', 'chakra_throat', 'chakra_crown'],
    element: ['element_water', 'element_wind'],
    zodiac: ['zodiac_leo', 'zodiac_scorpio', 'zodiac_sagittarius'],
  },
  LapisLazuli: {
    displayName: '青金石 (Lapis Lazuli)',
    englishName: 'Lapis Lazuli',
    availableColors: ["Deep Blue", "Royal Blue", "Azure Blue", "Blue with Gold Flecks"],
    specificInclusions: ["inclusion_pyrite_flecks_lapis", "inclusion_calcite_veins_lapis", "inclusion_sodalite_lapis_specific", "inclusion_diopside_lapis_specific", "inclusion_hauyne_lapis"],
    healingProperties: ["prop_wisdom", "prop_truth", "prop_communication", "prop_inner_peace"],
    chakra: ["chakra_throat", "chakra_thirdEye"],
    element: ["element_water", "element_air"],
    zodiac: ["zodiac_sagittarius", "zodiac_libra", "zodiac_taurus"]
  },
  Lepidolite: {
    displayName: '锂云母 (Lepidolite)',
    englishName: 'Lepidolite',
    availableColors: ['Lilac', 'Pink', 'Purple', 'Greyish'],
    specificInclusions: ['inclusion_mica_sheets_lepidolite', 'inclusion_scaly_aggregates_lepidolite', 'inclusion_tourmaline_lepidolite'],
    healingProperties: ['prop_natural_lithium_anxiety', 'prop_emotional_balance_soothing', 'prop_transition_stone', 'prop_clears_blockages'],
    chakra: ['chakra_heart', 'chakra_thirdEye', 'chakra_crown'],
    element: ['element_water', 'element_air'],
    zodiac: ['zodiac_libra', 'zodiac_pisces']
  },
  Malachite: {
    displayName: '孔雀石 (Malachite)',
    englishName: 'Malachite',
    availableColors: ["Green", "Banded Green (light to dark)", "Dark Green"],
    specificInclusions: ["inclusion_concentric_bands_malachite_specific", "inclusion_swirling_patterns_malachite_specific", "inclusion_botryoidal_formation_malachite", "inclusion_azurite_intergrowth_malachite_specific", "inclusion_fibrous_radiating_malachite"],
    healingProperties: ["prop_transformation_change", "prop_heart_healing", "prop_protection_negative_energies", "prop_spiritual_growth_malachite"],
    chakra: ["chakra_heart", "chakra_solarPlexus", "chakra_throat"],
    element: ["element_earth", "element_fire"],
    zodiac: ["zodiac_capricorn", "zodiac_scorpio", "zodiac_taurus"]
  },
  Moonstone: {
    displayName: '月光石 (Moonstone)',
    englishName: 'Moonstone',
    availableColors: ['White', 'Blue Sheen', 'Rainbow', 'Peach', 'Grey', 'Yellow', 'Pink'],
    specificInclusions: ['inclusion_centipede_moonstone', 'inclusion_adularescence_effect_moonstone', 'inclusion_black_tourmaline_moonstone'],
    healingProperties: ['prop_new_beginnings', 'prop_intuition', 'prop_feminine_energy', 'prop_emotional_balance'],
    chakra: ['chakra_sacral', 'chakra_thirdEye', 'chakra_crown'],
    element: ['element_water'],
    zodiac: ['zodiac_cancer', 'zodiac_libra', 'zodiac_scorpio'],
  },
  Morganite: {
    displayName: '摩根石 (Morganite)',
    englishName: 'Morganite',
    availableColors: ['Pink', 'Peach', 'Light Pink', 'Rose Pink'],
    specificInclusions: ['inclusion_parallel_growth_tubes_morganite', 'inclusion_liquid_inclusions_morganite'],
    healingProperties: ['prop_divine_love_morganite', 'prop_attracts_love_maintains_it', 'prop_emotional_healing_heart', 'prop_patience_reverence'],
    chakra: ['chakra_heart'],
    element: ['element_water'],
    zodiac: ['zodiac_pisces', 'zodiac_taurus', 'zodiac_cancer']
  },
  MossAgate: {
    displayName: '苔藓玛瑙 (Moss Agate)',
    englishName: 'Moss Agate',
    availableColors: ['Clear with green inclusions', 'White with green inclusions', 'Greenish blue'],
    specificInclusions: ['inclusion_dendritic_manganese_iron_moss', 'inclusion_green_hornblende_moss'],
    healingProperties: ['prop_stability_grounding_moss', 'prop_connection_to_nature', 'prop_abundance_growth_moss', 'prop_new_beginnings_moss'],
    chakra: ['chakra_heart', 'chakra_root'],
    element: ['element_earth'],
    zodiac: ['zodiac_virgo', 'zodiac_gemini']
  },
  Obsidian: {
    displayName: '黑曜石 (Obsidian)',
    englishName: 'Obsidian',
    availableColors: ['Black', 'Snowflake (Black with white spots)', 'Rainbow', 'Golden Sheen', 'Silver Sheen'],
    specificInclusions: ['inclusion_cristobalite_snowflake', 'inclusion_gas_bubbles_sheen', 'inclusion_conchoidal_fracture'],
    healingProperties: ['prop_powerful_cleansing', 'prop_truth_enhancing', 'prop_psychic_protection', 'prop_grounding_root'],
    chakra: ['chakra_root'],
    element: ['element_earth', 'element_fire'],
    zodiac: ['zodiac_scorpio', 'zodiac_sagittarius'],
  },
  Onyx: {
    displayName: '黑玛瑙 (Onyx)',
    englishName: 'Onyx',
    availableColors: ['Black', 'Banded Black and White', 'White'],
    specificInclusions: ['inclusion_banding_onyx', 'inclusion_uniform_color_onyx'],
    healingProperties: ['prop_strength_giving', 'prop_centers_energy_aligns', 'prop_grief_support', 'prop_self_control_stamina'],
    chakra: ['chakra_root'],
    element: ['element_earth'],
    zodiac: ['zodiac_leo', 'zodiac_capricorn']
  },
  PhantomQuartz: {
    displayName: '幽灵水晶 (Phantom Quartz)',
    englishName: 'Phantom Quartz',
    availableColors: ['Clear with Green Phantoms', 'Clear with Red Phantoms', 'Clear with White Phantoms', 'Smoky with Phantoms', 'Amethyst with Phantoms'],
    specificInclusions: ['inclusion_chlorite_phantom_specific', 'inclusion_hematite_phantom_specific', 'inclusion_kaolinite_phantom_specific', 'inclusion_limonite_phantom_specific', 'inclusion_multiple_stacked_phantoms', 'inclusion_angel_wing_phantom_specific'],
    healingProperties: ['prop_growth_evolution', 'prop_past_life_recall', 'prop_overcoming_stagnation', 'prop_universal_awareness'],
    chakra: ['chakra_all', 'chakra_crown', 'chakra_root'],
    element: ['element_storm'],
    zodiac: ['zodiac_all']
  },
  Prehnite: {
    displayName: '葡萄石 (Prehnite)',
    englishName: 'Prehnite',
    availableColors: ['Light Green', 'Yellow-Green', 'Clear to White'],
    specificInclusions: ['inclusion_epidote_needles_prehnite', 'inclusion_botryoidal_prehnite'],
    healingProperties: ['prop_unconditional_love_heals_healer', 'prop_connects_to_higher_self', 'prop_decluttering', 'prop_calms_environment'],
    chakra: ['chakra_solarPlexus', 'chakra_heart'],
    element: ['element_earth', 'element_water'],
    zodiac: ['zodiac_libra', 'zodiac_virgo'],
  },
  Pyrite: {
    displayName: '黄铁矿 (Pyrite)',
    englishName: 'Pyrite',
    availableColors: ['Pale brass-yellow', 'Metallic Gold'],
    specificInclusions: ['inclusion_cubic_crystals_pyrite', 'inclusion_striations_pyrite_faces', 'inclusion_pyritohedron_shape'],
    healingProperties: ['prop_masculine_energy', 'prop_willpower_action', 'prop_manifests_abundance', 'prop_protection_shielding'],
    chakra: ['chakra_solarPlexus', 'chakra_sacral'],
    element: ['element_earth', 'element_fire'],
    zodiac: ['zodiac_leo']
  },
  RedJasper: {
    displayName: '红碧玉 (Red Jasper)',
    englishName: 'Red Jasper',
    availableColors: ['Brick Red', 'Deep Red', 'Red with dark streaks'],
    specificInclusions: ['inclusion_hematite_veins_redjasper', 'inclusion_conchoidal_fracture_jasper'],
    healingProperties: ['prop_nurturing_stone', 'prop_stamina_endurance', 'prop_grounding_stability_jasper', 'prop_kundalini_awakening'],
    chakra: ['chakra_root', 'chakra_sacral'],
    element: ['element_earth', 'element_fire'],
    zodiac: ['zodiac_aries', 'zodiac_scorpio']
  },
  Rhodochrosite: {
    displayName: '红纹石 (Rhodochrosite)',
    englishName: 'Rhodochrosite',
    availableColors: ['Pink with white bands', 'Rose Red', 'Light Pink'],
    specificInclusions: ['inclusion_white_bands_rhodo', 'inclusion_stalactitic_growth_rhodo'],
    healingProperties: ['prop_selfless_love_compassion', 'prop_heals_inner_child', 'prop_lifts_depression', 'prop_positive_attitude'],
    chakra: ['chakra_heart', 'chakra_solarPlexus'],
    element: ['element_fire', 'element_water'],
    zodiac: ['zodiac_leo', 'zodiac_scorpio']
  },
  Rhodonite: {
    displayName: '蔷薇辉石 (Rhodonite)',
    englishName: 'Rhodonite',
    availableColors: ['Pink with Black Veins', 'Rose Pink', 'Reddish Pink'],
    specificInclusions: ['inclusion_black_manganese_dendrites_rhodonite', 'inclusion_uneven_color_distribution_rhodonite'],
    healingProperties: ['prop_emotional_healer_first_aid', 'prop_grounds_energy_balances_yin_yang', 'prop_activates_heart_chakra', 'prop_forgiveness_unselfish_love'],
    chakra: ['chakra_heart', 'chakra_root'],
    element: ['element_fire', 'element_earth'],
    zodiac: ['zodiac_taurus', 'zodiac_leo']
  },
  RoseQuartz: {
    displayName: '粉晶 (Rose Quartz)',
    englishName: 'Rose Quartz',
    availableColors: ['Pink', 'Light Pink', 'Rose Pink', 'Pale Pink'],
    specificInclusions: ['inclusion_dumortierite_specific_rose', 'inclusion_asterism_star_rose', 'inclusion_rutile_fibers_rose'],
    healingProperties: ['prop_love', 'prop_compassion', 'prop_emotional_healing', 'prop_self_acceptance'],
    chakra: ['chakra_heart'],
    element: ['element_water'],
    zodiac: ['zodiac_taurus', 'zodiac_libra'],
  },
  RutilatedQuartz: {
    displayName: '发晶/兔毛水晶 (Rutilated Quartz)',
    englishName: 'Rutilated Quartz',
    availableColors: ['Clear with Gold Rutile', 'Clear with Silver Rutile', 'Clear with Red Rutile', 'Clear with Black Rutile', 'Clear with White Rutile', 'Smoky with Gold Rutile'],
    specificInclusions: ['inclusion_rutile_needles_gold_specific', 'inclusion_rutile_needles_silver_specific', 'inclusion_rutile_needles_red_specific', 'inclusion_rutile_needles_black_specific', 'inclusion_star_rutile_formation', 'inclusion_hematite_base_rutile_specific'],
    healingProperties: ['prop_amplification_intentions', 'prop_spiritual_growth_rutilated', 'prop_cleansing_energizing', 'prop_manifestation_attraction', 'prop_psychic_enhancement'],
    chakra: ['chakra_all', 'chakra_solarPlexus'],
    element: ['element_fire', 'element_air'],
    zodiac: ['zodiac_leo', 'zodiac_gemini', 'zodiac_taurus']
  },
  Selenite: {
    displayName: '透石膏 (Selenite)',
    englishName: 'Selenite',
    availableColors: ["White", "Translucent White", "Peach", "Orange", "Green (rare)"],
    specificInclusions: ["inclusion_sand_selenite_specific"], // Sand can be included in desert rose selenite
    healingProperties: ["prop_cleansing_aura", "prop_spiritual_connection", "prop_peace_calm", "prop_mental_clarity_selenite"],
    chakra: ["chakra_crown", "chakra_thirdEye", "chakra_soul_star"],
    element: ["element_water", "element_air"],
    zodiac: ["zodiac_taurus", "zodiac_cancer"]
  },
  SmokyQuartz: {
    displayName: '茶晶 (Smoky Quartz)',
    englishName: 'Smoky Quartz',
    availableColors: ["Light Brown", "Dark Brown", "Greyish Brown", "Blackish Brown", "Yellowish Brown"],
    specificInclusions: ["inclusion_rutile_needles_smoky", "inclusion_phantom_growth_smoky", "inclusion_goethite_smoky_specific"],
    healingProperties: ["prop_grounding", "prop_protection_negativity", "prop_stress_relief", "prop_detoxification"],
    chakra: ["chakra_root"],
    element: ["element_earth"],
    zodiac: ["zodiac_scorpio", "zodiac_sagittarius", "zodiac_capricorn"]
  },
  Sodalite: {
    displayName: '方钠石 (Sodalite)',
    englishName: 'Sodalite',
    availableColors: ['Rich Royal Blue', 'Blue with White Veins', 'Grey-Blue'],
    specificInclusions: ['inclusion_calcite_veins_sodalite', 'inclusion_tenebrescence_sodalite'],
    healingProperties: ['prop_logic_rationality', 'prop_emotional_balance_calms_panic', 'prop_enhances_intuition', 'prop_encourages_truthfulness'],
    chakra: ['chakra_throat', 'chakra_thirdEye'],
    element: ['element_water', 'element_air'],
    zodiac: ['zodiac_sagittarius', 'zodiac_virgo'],
  },
  StrawberryQuartz: {
    displayName: '草莓晶 (Strawberry Quartz)',
    englishName: 'Strawberry Quartz',
    availableColors: ['Pinkish Red', 'Red with Seeds', 'Light Pink', 'Deep Pink', 'Orange-Pink'],
    specificInclusions: ['inclusion_hematite_dots_strawberry', 'inclusion_goethite_flakes_strawberry', 'inclusion_lepidocrocite_threads_strawberry', 'inclusion_mica_sparkles_strawberry'],
    healingProperties: ['prop_love_joy', 'prop_amplifies_intentions', 'prop_soothing_energy', 'prop_self_love_understanding'],
    chakra: ['chakra_heart', 'chakra_root'],
    element: ['element_earth', 'element_fire'],
    zodiac: ['zodiac_libra', 'zodiac_aries', 'zodiac_scorpio'],
  },
  Sunstone: {
    displayName: '太阳石 (Sunstone)',
    englishName: 'Sunstone',
    availableColors: ['Orange', 'Red-Orange', 'Yellow', 'Brownish Orange', 'Pink', 'Peach', 'Green (rare)', 'Colorless with Aventurescence'],
    specificInclusions: ['inclusion_hematite_platelets_sunstone_specific', 'inclusion_goethite_platelets_sunstone_specific', 'inclusion_copper_platelets_sunstone_specific', 'inclusion_aventurescence_schiller_sunstone', 'inclusion_zircon_crystals_sunstone'],
    healingProperties: ['prop_leadership_joy', 'prop_vitality_energy', 'prop_empowerment_luck', 'prop_optimism_confidence'],
    chakra: ['chakra_sacral', 'chakra_solarPlexus'],
    element: ['element_fire'],
    zodiac: ['zodiac_leo', 'zodiac_libra', 'zodiac_sagittarius'],
  },
  SuperSeven: {
    displayName: '超七水晶 (Super Seven)',
    englishName: 'Super Seven',
    availableColors: ['Purple-dominant', 'Smoky with inclusions', 'Reddish clusters'],
    specificInclusions: ['inclusion_cacoxenite_super7', 'inclusion_goethite_super7', 'inclusion_lepidocrocite_super7', 'inclusion_amethyst_layers_super7', 'inclusion_smoky_quartz_zones_super7'],
    healingProperties: ['prop_spiritual_awakening', 'prop_psychic_abilities', 'prop_master_healer', 'prop_all_chakras_alignment'],
    chakra: ['chakra_all', 'chakra_crown', 'chakra_soul_star'],
    element: ['element_storm'],
    zodiac: ['zodiac_all'],
  },
  TigersEye: {
    displayName: '虎眼石 (Tiger\'s Eye)',
    englishName: 'Tiger\'s Eye',
    availableColors: ['Golden Brown', 'Blue', 'Red'],
    specificInclusions: ['inclusion_chatoyancy_tigereye', 'inclusion_limonite_staining_tigereye'],
    healingProperties: ['prop_courage_confidence', 'prop_protection_grounding', 'prop_mental_clarity_focus', 'prop_willpower_motivation'],
    chakra: ['chakra_solarPlexus', 'chakra_sacral', 'chakra_root'],
    element: ['element_fire', 'element_earth'],
    zodiac: ['zodiac_capricorn', 'zodiac_leo', 'zodiac_gemini'],
  },
  Turquoise: {
    displayName: '绿松石 (Turquoise)',
    englishName: 'Turquoise',
    availableColors: ["Sky Blue", "Blue-Green", "Green", "Robin's Egg Blue"],
    specificInclusions: ["inclusion_limonite_matrix_turquoise", "inclusion_sandstone_matrix_turquoise", "inclusion_pyrite_crystals_turquoise", "inclusion_spiderweb_matrix_turquoise", "inclusion_quartz_veinlets_turquoise"],
    healingProperties: ["prop_protection_travel", "prop_healing_master", "prop_communication_throat", "prop_spiritual_attunement"],
    chakra: ["chakra_throat", "chakra_thirdEye"],
    element: ["element_earth", "element_air", "element_fire"],
    zodiac: ["zodiac_sagittarius", "zodiac_pisces", "zodiac_scorpio"]
  }
};
